### ISSUE TITLE
读取rinex异常问题

### ISSUE THREAD

**Issue by WangWorkHard** [liudmila-sherstnyakova/rinex-reader#3]
测试当任意卫星系统仅有一颗卫星时，会提示读取失败：
‘IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed’
测试截图及观测量文件已上传。
![error](https://github.com/liudmila-sherstnyakova/rinex-reader/assets/138084628/11f3bbfb-7480-4cd0-af04-d66c3806e498)
[test.txt](https://github.com/liudmila-sherstnyakova/rinex-reader/files/11901540/test.txt)

**Comment by liudmila-sherstnyakova** [comment]
@WangWorkHard Thank you for your attention! This bug is now fixed and version 1.0.1 should  work fine on the blocks with single satellite.

**Comment by WangWorkHard** [comment]
Okay, thanks for your share,Looking forward to updates.
